package com.example.feature.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary: Color = Color(0xFF4356B9)
val md_theme_light_onPrimary: Color = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer: Color = Color(0xFFDEE0FF)
val md_theme_light_onPrimaryContainer: Color = Color(0xFF00105A)
val md_theme_light_secondary: Color = Color(0xFF446813)
val md_theme_light_onSecondary: Color = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer: Color = Color(0xFFC4F18C)
val md_theme_light_onSecondaryContainer: Color = Color(0xFF102000)
val md_theme_light_tertiary: Color = Color(0xFF5B6400)
val md_theme_light_onTertiary: Color = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer: Color = Color(0xFFDCED4E)
val md_theme_light_onTertiaryContainer: Color = Color(0xFF1A1E00)
val md_theme_light_error: Color = Color(0xFFBA1A1A)
val md_theme_light_errorContainer: Color = Color(0xFFFFDAD6)
val md_theme_light_onError: Color = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer: Color = Color(0xFF410002)
val md_theme_light_background: Color = Color(0xFFFFFBFF)
val md_theme_light_onBackground: Color = Color(0xFF24005A)
val md_theme_light_surface: Color = Color(0xFFFFFBFF)
val md_theme_light_onSurface: Color = Color(0xFF24005A)
val md_theme_light_surfaceVariant: Color = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant: Color = Color(0xFF46464F)
val md_theme_light_outline: Color = Color(0xFF767680)
val md_theme_light_inverseOnSurface: Color = Color(0xFFF6EDFF)
val md_theme_light_inverseSurface: Color = Color(0xFF3A1D71)
val md_theme_light_inversePrimary: Color = Color(0xFFBAC3FF)
val md_theme_light_shadow: Color = Color(0xFF000000)
val md_theme_light_surfaceTint: Color = Color(0xFF4356B9)
val md_theme_light_outlineVariant: Color = Color(0xFFC6C5D0)
val md_theme_light_scrim: Color = Color(0xFF000000)

val seed: Color = Color(0xFF3D50B3)
