/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru._0xdc.gradle.metaspace.test

import java.io.File
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.io.TempDir
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource
import ru._0xdc.gradle.metaspace.test.util.TestUtils

@Disabled("Enable to test a project without a version catalog")
class SimpleFunctionalTest {
    @field:TempDir
    lateinit var projectDir: File

    @ParameterizedTest
    @MethodSource("invocationNumber")
    fun `test project without version catalog`(invocationNumber: Int) {
        val result = TestUtils.buildProject("android-app-simple", projectDir)
        assert(result.output.contains("BUILD SUCCESSFUL"))
    }
    private companion object {
        @JvmStatic
        fun invocationNumber(): List<Int> = (1..   30).toList()
    }
}
