/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru._0xdc.gradle.metaspace.test

import org.gradle.api.Project
import org.gradle.api.Plugin

class GradleMetaspaceTestPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'ru._0xdc.gradle.metaspace.test.greeting'")
            }
        }
    }
}
