/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.transformaction

import org.gradle.api.Project
import org.gradle.api.Plugin

class TransformactionPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'com.example.transformaction.greeting'")
            }
        }
    }
}
