name: Build

on:
  push:
    branches: [ "bug-agp-800-alpha11-managedDevicesTestNames" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Install emulators
        run: |
         yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;aosp_atd;x86" --sdk_root=${ANDROID_SDK_ROOT}
         yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Running tests
        run: ./gradlew --info --stacktrace -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect pixel2api30DebugAndroidTest

