name: build

on:
  push:
    branches:
      - 'bug-kmp-gradle-tests'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-13, macos-latest, ubuntu-latest ]
      fail-fast: false
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '24'

      - name: Run test
        run: ./gradlew app:check --rerun-tasks --stacktrace
